### ISSUE TITLE
Add yarn support

### ISSUE THREAD

**Issue by raphaelokon** [pattern-lab/patternlab-node-cli#1]
Add support for project that use yarn package manager instead of npm.

**Comment by raphaelokon** [comment]
Removing milestone as this one is a complicated one … needs pre-init definition which package manager is being used.

**Comment by bmuenzenmeyer** [comment]
> Removing milestone as this one is a complicated one … needs pre-init definition which package manager is being used.

I am interested in doing this within core too - but dont understand your comment. Could you help me understand what you mean?

**Comment by raphaelokon** [comment]
Well … you need to determine whether the user is using `npm` or `yarn` to do the auto-installation of packages during `patternlab init`. So you either ask the user to use another mechanism to determine the package manager in use.

**Comment by bmuenzenmeyer** [comment]
ah i see - it's an `init` command problem, not with installation of the CLI itself

**Comment by raphaelokon** [comment]
@bmuenzenmeyer Exactly. Not even an `init` problem … it is a deterministic problem in order to choose the correct package manager.

**Comment by raphaelokon** [comment]
https://github.com/sindresorhus/has-yarn looks promising in order to detect which package manager is being used.

**Comment by benhalverson** [comment]
@raphaelokon checkout https://github.com/storybooks/getstorybook/blob/master/bin/generate.js to see how getstorybook decides on when to use yarn vs npm

**Comment by raphaelokon** [comment]
Thanks, but I already had this implemented locally …

```js
const useYarn = hasYarn();
const pm = useYarn ? 'yarn' : 'npm';
const installCmd = useYarn ? 'add' : 'install';
// …
```

**Comment by raphaelokon** [comment]
Added via e50fb06
