### ISSUE TITLE
patternlab serve should not watch for changes

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node-cli#12]
`patternlab serve` launches BrowserSync, which reports that it is watching for changes. 

Long-term, this should not be the responsibility of the CLI, nor the `serve1 command.

**Comment by raphaelokon** [comment]
Agreed.

**Comment by bmuenzenmeyer** [comment]
@raphaelokon Running `patternlab serve` still emits console output of 

`[BS] Watching files..` when in fact it does not.

I'll have to double check, but is there a possibility this is coming from the CLI still?

**Comment by benhalverson** [comment]
@bmuenzenmeyer what should the command be for watching for changes?

**Comment by raphaelokon** [comment]
@benhalverson We already have this reflected in https://github.com/pattern-lab/patternlab-node-cli/issues/23 and I am on it https://github.com/pattern-lab/patternlab-node-cli/projects/1

There is and was a lot of discussion in our node-team on Gitter.
