### ISSUE TITLE
Starterkit installation fails for any starterkit without a package.json

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node-cli#15]
https://github.com/pattern-lab/patternlab-node-cli/blob/master/bin/init.js#L101-L160

- [x] https://github.com/pattern-lab/starterkit-mustache-demo
- [x] https://github.com/pattern-lab/starterkit-mustache-base
- [x] https://github.com/pattern-lab/starterkit-mustache-acidtest
- [x] https://github.com/pattern-lab/starterkit-mustache-foundation
- [x] https://github.com/pattern-lab/starterkit-mustache-bootstrap
- [x] https://github.com/pattern-lab/starterkit-mustache-materialdesign

**Comment by raphaelokon** [comment]
@bmuenzenmeyer Can you explain on this one?

**Comment by bmuenzenmeyer** [comment]
so we've had problems with npm/requiring starterkits in the past because their `package.json` files were missing a `main` entrypoint. this was a placeholder issue to make mention of all "official" starterkits that are still to be changed, like: https://github.com/pattern-lab/starterkit-mustache-bootstrap

i will turn this into a to-do list

**Comment by raphaelokon** [comment]
Oh I missed that, thanks! I will also try to think about a way to check for existence without a `main` in package.json

**Comment by raphaelokon** [comment]
@bmuenzenmeyer I noticed that https://github.com/pattern-lab/starterkit-mustache-base cannot be installed via `npm` because no `package.json` …

**Comment by bmuenzenmeyer** [comment]
@raphaelokon all starterkits are done. feel free to retest that suite you showed me earlier and close this if it looks good

**Comment by raphaelokon** [comment]
@bmuenzenmeyer Cheers for updating the starter kits

**Comment by raphaelokon** [comment]
https://github.com/pattern-lab/starterkit-mustache-materialdesign/blob/master/package.json This one is still missing a `main` I guess

**Comment by bmuenzenmeyer** [comment]
ugh. repushed. check again! off to bed for me

**Comment by raphaelokon** [comment]
Enjoy! Works now – tests do pass. This will be fixed with the next bigger release.

**Comment by raphaelokon** [comment]
Closing as this is a won't fix for global installs until we hit #32
