### ISSUE TITLE
Implement CLI method(s): StarterKits

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node-cli#16]
> braindump, intended to start discussion. nothing here is prescriptive.

At any time, a user should be able to ask the PL CLI what starterkits are available for download.

Current exposed command on editions: 

* https://github.com/pattern-lab/patternlab-node/blob/dev/core/lib/patternlab.js#L528-L530 
* https://github.com/pattern-lab/edition-node-gulp/blob/master/gulpfile.js#L115-L118

Proposed CLI command:
`patternlab starterkit --install`

With no additional parameters, perhaps it suggest like https://github.com/pattern-lab/patternlab-node-cli/blob/master/bin/init.js#L236

Proposed option:
`patternlab starterkit --install --starterkit-mustache-demo`

With this option, it reaches out to install from npm if needed, and then installs similar to 
* https://github.com/pattern-lab/patternlab-node/blob/dev/core/lib/patternlab.js#L531-L533
* https://github.com/pattern-lab/edition-node-gulp/blob/master/gulpfile.js#L120-L123

**Comment by raphaelokon** [comment]
I have those implemented but took them out to have a minimal set of features to start with. I will reintroduce them.
