### ISSUE TITLE
Implement CLI method(s): Plugin

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node-cli#17]
> braindump, intended to start discussion. nothing here is prescriptive.

At any time, a user should be able to install a plugin.

Current exposed command on editions/core: 

* https://github.com/pattern-lab/patternlab-node/blob/dev/core/lib/patternlab.js#L534-L536
* https://github.com/pattern-lab/edition-node-gulp/blob/master/gulpfile.js#L129-L132

Plugin installation is a bit one-two stepped right now, with users needing to `npm install` first and then either call the above or even `npm run postinstall`, so it'd be nice if we could get all that into one method.

`patternlab plugin --install --plugin-node-tab`

This could reach out to npm if plugin-node-tab is not found already locally, and do everything for the user.

Future commands to enable/disable would be nice too, as mentioned here: https://github.com/pattern-lab/plugin-node-tab#enabling--disabling-the-plugin

**Comment by raphaelokon** [comment]
I disagree with the CLI commands here. The cmd switches should not represent an action **and** the argument passed to that action (`--install, --plugin-node-tab`)
I am more in favor of subcommands – https://github.com/tj/commander.js/#git-style-sub-commands. This would also play nicely with enable/disable logic later on.

Also to consider installing multiple plugins at once `--plugins=plugin-node-tab, plugin-xyz`

**Comment by bmuenzenmeyer** [comment]
@raphaelokon oooo that's neat 👀 

:+1:
