### ISSUE TITLE
patternlab -v vs patternlab -V

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node-cli#21]
### General information

- NodeJS version: 5.5.0
- NPM version: 3.3.12

### Problem description
According to the documentation, I should be able to run `patternlab -V` to emit the CLI version. Other commands have this lowercased, such as help and config. Is there a reason why this is inconsistent, or is it just the README that needs updating. I'd think that lowercase is preferred in most cases, if not both. 

 -----

**disregard most of above, kept for records...**

I did a `patternlab -h` to see how it emits the help and just now noticed the verbose flag, so perhaps only the documentation needs updating to explain that option too.

**Comment by raphaelokon** [comment]
Thanks @bmuenzenmeyer – good point! Will add docs for it.
