### ISSUE TITLE
Add interactive patternlab-config.json guide

### ISSUE THREAD

**Issue by raphaelokon** [pattern-lab/patternlab-node-cli#25]
![pl](https://cloud.githubusercontent.com/assets/527631/21923856/a5614012-d976-11e6-85af-af0ee55dbae6.gif)

**Comment by bmuenzenmeyer** [comment]
Wow @raphaelokon this is great!

Does the right side support markdown?

**Comment by raphaelokon** [comment]
Currently no. It is generated from a JSON to make it possible mapping over the `patternlab-config.json`.

**Comment by raphaelokon** [comment]
Closing as this is considered to be implemented into the `core` rather than the `cli`

**Comment by bmuenzenmeyer** [comment]
Whatever happened to that code above then?

**Comment by raphaelokon** [comment]
Hi @bmuenzenmeyer – haven't touched it yet :-) I descoped that to make free time for the CLI. 

It generates the HTML via Pug (Jade) from a JSON that is a patternlab-config.json with some additional keys added to it for the explanation of the keys.

I can share that code if you like.
