### ISSUE TITLE
Discuss miscellaneous browsersync configuration

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node-cli#26]
watches have already been discussed inside https://github.com/pattern-lab/patternlab-node-cli/issues/23

I am going to break down the remaining browsersync config on the `patternlab:connect` gulp task found within edition-node-gulp's gulpfile: https://github.com/pattern-lab/edition-node-gulp/blob/master/gulpfile.js

```
gulp.task('patternlab:connect', gulp.series(function(done) {
  browserSync.init({
    server: {
      baseDir: resolvePath(paths().public.root)
    },
    snippetOptions: {
      // Ignore all HTML files within the templates folder
      blacklist: ['/index.html', '/', '/?*']
    },
    notify: {
      styles: [
        'display: none',
        'padding: 15px',
        'font-family: sans-serif',
        'position: fixed',
        'font-size: 1em',
        'z-index: 9999',
        'bottom: 0px',
        'right: 0px',
        'border-top-left-radius: 5px',
        'background-color: #1B2032',
        'opacity: 0.4',
        'margin: 0',
        'color: white',
        'text-align: center'
      ]
    }
  }, function(){
    console.log('PATTERN LAB NODE WATCHING FOR CHANGES');
    done();
  });
}));
```

```
    server: {
      baseDir: resolvePath(paths().public.root)
    },
```

the server `baseDir` command should map to the above always, which is again configurable by the user and supplied within `patternlab-config.json`

✔️ 

```
    snippetOptions: {
      // Ignore all HTML files within the templates folder
      blacklist: ['/index.html', '/', '/?*']
    },
```

this option prevents the PL chrome from refreshing, preserving a user's scroll position, while updating the iframe content (the patterns). we should be able to safely do this blackbox for users without any problem

✔️ 

```
    notify: {
      styles: [
        'display: none',
        'padding: 15px',
        'font-family: sans-serif',
        'position: fixed',
        'font-size: 1em',
        'z-index: 9999',
        'bottom: 0px',
        'right: 0px',
        'border-top-left-radius: 5px',
        'background-color: #1B2032',
        'opacity: 0.4',
        'margin: 0',
        'color: white',
        'text-align: center'
      ]
    }
```

Geoff added this override of the default snippet to make it less obtrusive for users. It could probably be blackboxed too. If someone really wants to change it, we can look into ways I suppose. Understanding what class, if any, there is on that, and if it's accessible via the `pattern-scaffold.css` file that we load might be all we need.

✔️ 

```
function(){
    console.log('PATTERN LAB NODE WATCHING FOR CHANGES');
    done();
  });
```

It'd be nice if we had a way to provide users with a callback like this after BS starts. I have a feeling, this being a CLI, that we will be able to do just that.

✔️ 

@raphaelokon does this help clarify what is needed, along with the other issue?

**Comment by raphaelokon** [comment]
This helps a lot. 

If you look into https://github.com/pattern-lab/patternlab-node-cli/blob/master/bin/preview.js you'll actually see that I already use some stuff from the config in there – like the `baseDir`

I also think that the serve functionality should be part of the core, not the CLI. The only reason we have `serve` in the CLI currently is because the core lacks it (and the CLI being a core wrapper needs to provide it for now). So ideally the serve functionality will be moved into the core, and the core exposing an~~d~~  API and encapsulating the required settings you mentioned above.

>It'd be nice if we had a way to provide users with a callback like this after BS starts. I have a feeling, this being a CLI, that we will be able to do just that.

Not sure if I understand this correctly – the CLI cannot expose a `callback` since it is just working from the command line

**Comment by raphaelokon** [comment]
I am closing this – we discussed the bits via Gitter.
