### ISSUE TITLE
Extend patternlab --version to also report the core version

### ISSUE THREAD

**Issue by bmuenzenmeyer** [pattern-lab/patternlab-node-cli#42]
### General information

- NodeJS version: 6.9.5
- NPM version: 3.5.2

### Problem description

With the patternlab cli, there is no way to report the current core version. Today people can do this with `gulp patternlab:version`

Now that I am removing PL boilerplate logs (https://github.com/pattern-lab/patternlab-node/issues/636) it would be nice if the CLI could also report the version of core. 
This would be similar to how `gulp -v` works too (which reports the local and then the global version)

### Reproduction steps
`patternlab --version`

**Comment by raphaelokon** [comment]
@bmuenzenmeyer Problem is that core doen't provide an API for retrieving its version … 
```js
pl().version() //=> Logs to stdout rather than returning a string
```
https://github.com/pattern-lab/patternlab-node/blob/master/core/lib/patternlab.js#L180-L182

The core should probably just provide the version number and let the consumer decide how to use it.

**Comment by raphaelokon** [comment]
@bmuenzenmeyer Any news on that one?

**Comment by bmuenzenmeyer** [comment]
@raphaelokon I'd refer to https://github.com/pattern-lab/patternlab-node/commit/b638ad0198b4ae2bcfcdfabec8a525613429d293

sounds as if you agree in concept that is works. Can you test against `dev-3.0` to confirm ?

**Comment by raphaelokon** [comment]
LGTM. I haven't pulled it yet. But this seems like a breaking API change as `pl().version()` now returns a string and not to `stderr`. Maybe keep the signature of `pl().version()` and just add the `pl().v()`with the new functionality—is this landing in v3 or prior?

**Comment by bmuenzenmeyer** [comment]
I like the idea of re-orienting the current method `pl().version()` toward your use case. Therefore, it is in v3 and a breaking change

**Comment by raphaelokon** [comment]
Cheers.

**Comment by raphaelokon** [comment]
Any ideas of making this a static func instead of an instance func?
