### ISSUE TITLE
Re-add support for Node v4

### ISSUE THREAD

**Issue by raphaelokon** [pattern-lab/patternlab-node-cli#45]
Should we re-add support for Node v4?
/cc @bmuenzenmeyer

**Comment by bmuenzenmeyer** [comment]
no, not in my opinion

https://github.com/pattern-lab/patternlab-node/commit/ab99d50e0f5ffbc117f0a9b8cb5d602e7232dc49

**Comment by raphaelokon** [comment]
Cheers! Agreed. I added an alpha release which supports v4 … mainly for backcompat.
