### ISSUE TITLE
starterkit-mustache-demo are always fetch on `init`

### ISSUE THREAD

**Issue by raphaelokon** [pattern-lab/patternlab-node-cli#7]
Add a check if starter kits are already present in `node_modules`

**Comment by raphaelokon** [comment]
@bmuenzenmeyer This one fails because `require('starterkit-mustache-demo')` cannot find `starterkit-mustache-demo` as a module. We had the same problem with `edition-node` – because those modules likely do not have an entry point, in which case `require` doesn't recognize the module being already present in `node_modules`

**Comment by bmuenzenmeyer** [comment]
confirmed - https://github.com/pattern-lab/starterkit-mustache-demo/blob/master/package.json 

on it

**Comment by bmuenzenmeyer** [comment]
@raphaelokon please retest.

note every starterkit will need this same fix applied to it

**Comment by raphaelokon** [comment]
Cheers. Will do!

**Comment by raphaelokon** [comment]
This saved it … we probably need a better check in future but it is good to go for now. Thanks @bmuenzenmeyer
